# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import hdfs_pb2 as protos_dot_hdfs__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/hdfs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FullServicesStub(object):
    """Definición del servicio FullServices
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DataNodeDesignationNameNodeClient = channel.unary_unary(
                '/hdfs.FullServices/DataNodeDesignationNameNodeClient',
                request_serializer=protos_dot_hdfs__pb2.DataNodeDesignationClientRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.DataNodeDesignationNameNodeResponse.FromString,
                _registered_method=True)
        self.BlockReportNameNodeDataNode = channel.unary_unary(
                '/hdfs.FullServices/BlockReportNameNodeDataNode',
                request_serializer=protos_dot_hdfs__pb2.BlockReportDataNodeRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.BlockReportNameNodeResponse.FromString,
                _registered_method=True)
        self.FileLocationNameNodeClient = channel.unary_unary(
                '/hdfs.FullServices/FileLocationNameNodeClient',
                request_serializer=protos_dot_hdfs__pb2.FileLocationClientRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.FileLocationNameNodeResponse.FromString,
                _registered_method=True)
        self.BackUpNameNodeFollowerNameNodeLeader = channel.unary_unary(
                '/hdfs.FullServices/BackUpNameNodeFollowerNameNodeLeader',
                request_serializer=protos_dot_hdfs__pb2.BackUpNameNodeLeaderRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.BackUpNameNodeFollowerResponse.FromString,
                _registered_method=True)
        self.HandShakeNameNodeDataNode = channel.unary_unary(
                '/hdfs.FullServices/HandShakeNameNodeDataNode',
                request_serializer=protos_dot_hdfs__pb2.HandShakeDataNodeRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.HandShakeNameNodeResponse.FromString,
                _registered_method=True)
        self.HeartBeatNameNodeDataNode = channel.unary_unary(
                '/hdfs.FullServices/HeartBeatNameNodeDataNode',
                request_serializer=protos_dot_hdfs__pb2.HeartBeatDataNodeRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.HeartBeatNameNodeResponse.FromString,
                _registered_method=True)
        self.DownloadFileDataNodeClient = channel.unary_unary(
                '/hdfs.FullServices/DownloadFileDataNodeClient',
                request_serializer=protos_dot_hdfs__pb2.DownloadFileClientRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.DownloadFileDataNodeResponse.FromString,
                _registered_method=True)
        self.UploadFileDataNodeClient = channel.unary_unary(
                '/hdfs.FullServices/UploadFileDataNodeClient',
                request_serializer=protos_dot_hdfs__pb2.UploadFileClientRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.UploadFileDataNodeResponse.FromString,
                _registered_method=True)
        self.DeleteFileDataNodeClient = channel.unary_unary(
                '/hdfs.FullServices/DeleteFileDataNodeClient',
                request_serializer=protos_dot_hdfs__pb2.DeleteFileClientRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.DeleteFileDataNodeResponse.FromString,
                _registered_method=True)
        self.ReadFileDataNodeClient = channel.unary_unary(
                '/hdfs.FullServices/ReadFileDataNodeClient',
                request_serializer=protos_dot_hdfs__pb2.ReadFileClientRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.ReadFileDataNodeResponse.FromString,
                _registered_method=True)
        self.PipeLineDataNodeResponseDataNodeRequest = channel.unary_unary(
                '/hdfs.FullServices/PipeLineDataNodeResponseDataNodeRequest',
                request_serializer=protos_dot_hdfs__pb2.PipeLineDataNodeRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.PipeLineDataNodeResponse.FromString,
                _registered_method=True)
        self.DeleteFileNameNodeDataNode = channel.unary_unary(
                '/hdfs.FullServices/DeleteFileNameNodeDataNode',
                request_serializer=protos_dot_hdfs__pb2.DeleteFileDataNodeRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.DeleteFileNameNodeResponse.FromString,
                _registered_method=True)
        self.PipeLineForGetDataNodeResponseDataNodeRequest = channel.unary_unary(
                '/hdfs.FullServices/PipeLineForGetDataNodeResponseDataNodeRequest',
                request_serializer=protos_dot_hdfs__pb2.PipeLineForGetDataNodeRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.PipeLineForGetDataNodeResponse.FromString,
                _registered_method=True)
        self.PipeLineForDeleteDataNodeResponseDataNodeRequest = channel.unary_unary(
                '/hdfs.FullServices/PipeLineForDeleteDataNodeResponseDataNodeRequest',
                request_serializer=protos_dot_hdfs__pb2.PipeLineForDeleteDataNodeRequest.SerializeToString,
                response_deserializer=protos_dot_hdfs__pb2.PipeLineForDeleteDataNodeResponse.FromString,
                _registered_method=True)


class FullServicesServicer(object):
    """Definición del servicio FullServices
    """

    def DataNodeDesignationNameNodeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockReportNameNodeDataNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileLocationNameNodeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackUpNameNodeFollowerNameNodeLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandShakeNameNodeDataNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartBeatNameNodeDataNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFileDataNodeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFileDataNodeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFileDataNodeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFileDataNodeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PipeLineDataNodeResponseDataNodeRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFileNameNodeDataNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PipeLineForGetDataNodeResponseDataNodeRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PipeLineForDeleteDataNodeResponseDataNodeRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FullServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DataNodeDesignationNameNodeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DataNodeDesignationNameNodeClient,
                    request_deserializer=protos_dot_hdfs__pb2.DataNodeDesignationClientRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.DataNodeDesignationNameNodeResponse.SerializeToString,
            ),
            'BlockReportNameNodeDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockReportNameNodeDataNode,
                    request_deserializer=protos_dot_hdfs__pb2.BlockReportDataNodeRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.BlockReportNameNodeResponse.SerializeToString,
            ),
            'FileLocationNameNodeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.FileLocationNameNodeClient,
                    request_deserializer=protos_dot_hdfs__pb2.FileLocationClientRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.FileLocationNameNodeResponse.SerializeToString,
            ),
            'BackUpNameNodeFollowerNameNodeLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.BackUpNameNodeFollowerNameNodeLeader,
                    request_deserializer=protos_dot_hdfs__pb2.BackUpNameNodeLeaderRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.BackUpNameNodeFollowerResponse.SerializeToString,
            ),
            'HandShakeNameNodeDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.HandShakeNameNodeDataNode,
                    request_deserializer=protos_dot_hdfs__pb2.HandShakeDataNodeRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.HandShakeNameNodeResponse.SerializeToString,
            ),
            'HeartBeatNameNodeDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartBeatNameNodeDataNode,
                    request_deserializer=protos_dot_hdfs__pb2.HeartBeatDataNodeRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.HeartBeatNameNodeResponse.SerializeToString,
            ),
            'DownloadFileDataNodeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFileDataNodeClient,
                    request_deserializer=protos_dot_hdfs__pb2.DownloadFileClientRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.DownloadFileDataNodeResponse.SerializeToString,
            ),
            'UploadFileDataNodeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFileDataNodeClient,
                    request_deserializer=protos_dot_hdfs__pb2.UploadFileClientRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.UploadFileDataNodeResponse.SerializeToString,
            ),
            'DeleteFileDataNodeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFileDataNodeClient,
                    request_deserializer=protos_dot_hdfs__pb2.DeleteFileClientRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.DeleteFileDataNodeResponse.SerializeToString,
            ),
            'ReadFileDataNodeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFileDataNodeClient,
                    request_deserializer=protos_dot_hdfs__pb2.ReadFileClientRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.ReadFileDataNodeResponse.SerializeToString,
            ),
            'PipeLineDataNodeResponseDataNodeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.PipeLineDataNodeResponseDataNodeRequest,
                    request_deserializer=protos_dot_hdfs__pb2.PipeLineDataNodeRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.PipeLineDataNodeResponse.SerializeToString,
            ),
            'DeleteFileNameNodeDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFileNameNodeDataNode,
                    request_deserializer=protos_dot_hdfs__pb2.DeleteFileDataNodeRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.DeleteFileNameNodeResponse.SerializeToString,
            ),
            'PipeLineForGetDataNodeResponseDataNodeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.PipeLineForGetDataNodeResponseDataNodeRequest,
                    request_deserializer=protos_dot_hdfs__pb2.PipeLineForGetDataNodeRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.PipeLineForGetDataNodeResponse.SerializeToString,
            ),
            'PipeLineForDeleteDataNodeResponseDataNodeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.PipeLineForDeleteDataNodeResponseDataNodeRequest,
                    request_deserializer=protos_dot_hdfs__pb2.PipeLineForDeleteDataNodeRequest.FromString,
                    response_serializer=protos_dot_hdfs__pb2.PipeLineForDeleteDataNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hdfs.FullServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hdfs.FullServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FullServices(object):
    """Definición del servicio FullServices
    """

    @staticmethod
    def DataNodeDesignationNameNodeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/DataNodeDesignationNameNodeClient',
            protos_dot_hdfs__pb2.DataNodeDesignationClientRequest.SerializeToString,
            protos_dot_hdfs__pb2.DataNodeDesignationNameNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockReportNameNodeDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/BlockReportNameNodeDataNode',
            protos_dot_hdfs__pb2.BlockReportDataNodeRequest.SerializeToString,
            protos_dot_hdfs__pb2.BlockReportNameNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileLocationNameNodeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/FileLocationNameNodeClient',
            protos_dot_hdfs__pb2.FileLocationClientRequest.SerializeToString,
            protos_dot_hdfs__pb2.FileLocationNameNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackUpNameNodeFollowerNameNodeLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/BackUpNameNodeFollowerNameNodeLeader',
            protos_dot_hdfs__pb2.BackUpNameNodeLeaderRequest.SerializeToString,
            protos_dot_hdfs__pb2.BackUpNameNodeFollowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandShakeNameNodeDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/HandShakeNameNodeDataNode',
            protos_dot_hdfs__pb2.HandShakeDataNodeRequest.SerializeToString,
            protos_dot_hdfs__pb2.HandShakeNameNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartBeatNameNodeDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/HeartBeatNameNodeDataNode',
            protos_dot_hdfs__pb2.HeartBeatDataNodeRequest.SerializeToString,
            protos_dot_hdfs__pb2.HeartBeatNameNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFileDataNodeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/DownloadFileDataNodeClient',
            protos_dot_hdfs__pb2.DownloadFileClientRequest.SerializeToString,
            protos_dot_hdfs__pb2.DownloadFileDataNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFileDataNodeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/UploadFileDataNodeClient',
            protos_dot_hdfs__pb2.UploadFileClientRequest.SerializeToString,
            protos_dot_hdfs__pb2.UploadFileDataNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFileDataNodeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/DeleteFileDataNodeClient',
            protos_dot_hdfs__pb2.DeleteFileClientRequest.SerializeToString,
            protos_dot_hdfs__pb2.DeleteFileDataNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFileDataNodeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/ReadFileDataNodeClient',
            protos_dot_hdfs__pb2.ReadFileClientRequest.SerializeToString,
            protos_dot_hdfs__pb2.ReadFileDataNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PipeLineDataNodeResponseDataNodeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/PipeLineDataNodeResponseDataNodeRequest',
            protos_dot_hdfs__pb2.PipeLineDataNodeRequest.SerializeToString,
            protos_dot_hdfs__pb2.PipeLineDataNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFileNameNodeDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/DeleteFileNameNodeDataNode',
            protos_dot_hdfs__pb2.DeleteFileDataNodeRequest.SerializeToString,
            protos_dot_hdfs__pb2.DeleteFileNameNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PipeLineForGetDataNodeResponseDataNodeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/PipeLineForGetDataNodeResponseDataNodeRequest',
            protos_dot_hdfs__pb2.PipeLineForGetDataNodeRequest.SerializeToString,
            protos_dot_hdfs__pb2.PipeLineForGetDataNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PipeLineForDeleteDataNodeResponseDataNodeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hdfs.FullServices/PipeLineForDeleteDataNodeResponseDataNodeRequest',
            protos_dot_hdfs__pb2.PipeLineForDeleteDataNodeRequest.SerializeToString,
            protos_dot_hdfs__pb2.PipeLineForDeleteDataNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
